apiVersion: v1
kind: Service
metadata:
  name: campaignuserservice
  namespace: campaign-system
  labels:
    app.kubernetes.io/name: campaignuserservice
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: campaign-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: campaignuserservice
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
