<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DonationService.Application\DonationService.Application.csproj" />
    <ProjectReference Include="..\DonationService.Domain\DonationService.Domain.csproj" />
    <ProjectReference Include="..\DonationService.Contracts\DonationService.Contracts.csproj" />
    <ProjectReference Include="..\DonationService.SharedKernel\DonationService.SharedKernel.csproj" />
  </ItemGroup>

</Project>
