<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CampaignUserService.Application\CampaignUserService.Application.csproj" />
    <ProjectReference Include="..\CampaignUserService.Domain\CampaignUserService.Domain.csproj" />
    <ProjectReference Include="..\CampaignUserService.SharedKernel\CampaignUserService.SharedKernel.csproj" />
  </ItemGroup>

</Project>
